<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SWCE.Aplicatition\SWCE.Aplication.csproj" />
    <ProjectReference Include="..\SWCE.Infraestructure\SWCE.Infraestructure.csproj" />
    <ProjectReference Include="..\SWCE.Persistence\SWCE.Persistence.csproj" />
  </ItemGroup>

</Project>
